#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"
require File.expand_path('../../config/environment', __FILE__)

# Mailman.config.logger = Logger.new("log/mailman.log")

Mailman.config.pop3 = {
  username: Rails.configuration.x.email_polling.username,
  password: Rails.configuration.x.email_polling.password,
  server: 'pop.gmail.com',
  port: 995,
  ssl: true
}

Mailman::Application.run do
  default do
    begin
      Email.receive_mail(message)
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
